# Conclusiones {-}

De la aplicación del Sistema de Capacidad de Uso Agropecuario a las tierras de los estados Aragua, Carabobo y Yaracuy para sondear la aptitud preliminar de las tierras para cultivar cereales y leguminosas, se desprendieron las siguientes conclusiones.

* Se estudiaron 18.757 km2 de tierras de los estados Aragua, Carabobo y Yaracuy y de ellas 6.325 km2 son aptas desde el punto de vista físico natural en diferentes grados para cultivar cereales y leguminosas, es decir un 34 % aproximadamente. Sin embargo esta superficie se debe precisar extrayendo las superficies bajo uso particularmente excluyente como las poblaciones y áreas de régimen de administración especial (ABRAE) entre otras. 

* Una gran proporción de las tierras aptas para el cultivo de cereales y leguminosas se ubican en o próximas a centros poblados importantes como es el caso de la cuenca plana del lago de Valencia y el valle del río Yaracuy, en donde también se emplazan ciudades como Maracay, Valencia, La Victoria, San Diego, Naguanagua, San Felipe entre otras. Lo que podría conllevar a conflictos en el uso de las tierras y a disminuir la superficie estimada.

* El estado Aragua resultó ligeramente con una mayor proporción de tierras aptas para el cultivo de cereales y leguminosas entre los tres estados analizados. 

* Las principales limitaciones encontradas para el cultivo de cereales y leguminosas en estos estados, son por un lado las altas pendientes, micro relieve irregular, drenaje externo excesivo y poca fertilidad de los suelos de relieve de montañas y por otro lado los suelos mal drenados de planicies o valles planos cercanos a cursos de aguas.

**RECOMENDACIONES**

Algunas recomendaciones son:

* Calcular las superficies urbanas actuales y bajo régimen de administración especial (ABRAES) para obtener con precisión las áreas aptas para el cultivo de cereales y leguminosas y establecer las ventanas para evaluaciones de tierras específicas de Tipos de Utilización de las Tierras (TUT) relacionados con Cereales y leguminosas (Maíz, Sorgo, Arroz, Caraota, Frijol, entre otros).

* Realizar una evaluación de tierras físico natural y socioeconómica con las directivas de FAO, la cual contemplaría el estudio de cualidades de las tierras importantes como la humedad disponible,  empleando modelos agronómicos de balances hídricos.

* Mejorar la escala de estudio (más detalles) en las ventanas de tierras aptas establecidas en esta investigación, siempre y cuando exista información edáfica disponible o relativamente fácil de obtener.